esphome:
  name: esphome-web-cfx3
  friendly_name: ESPHome Dometic CFX3 WiFi
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://andrewbackway/esphome-dometic-cfx-wifi
    refresh: 1s

ota:
  - platform: esphome

wifi:
  ssid: !secrets wifi_ssid
  password: !secrets wifi_password
  
dometic_cfx_wifi:
  - id: fridge1
    host: 10.1.0.198

sensor:
  - platform: dometic_cfx_wifi
    dometic_cfx_wifi_id: fridge1
    type: COMPARTMENT_0_MEASURED_TEMPERATURE
    name: "Fridge 1 Temp"
    icon: "mdi:thermometer"
  - platform: dometic_cfx_wifi
    dometic_cfx_wifi_id: fridge1
    type: COMPARTMENT_0_SET_TEMPERATURE
    name: "Fridge 1 Target Temp"
    icon: "mdi:thermometer"
  - platform: dometic_cfx_wifi
    dometic_cfx_wifi_id: fridge1
    type: COMPARTMENT_1_MEASURED_TEMPERATURE
    name: "Fridge 2 Temp"
    icon: "mdi:thermometer"
  - platform: dometic_cfx_wifi
    dometic_cfx_wifi_id: fridge1
    type: COMPARTMENT_1_SET_TEMPERATURE
    name: "Fridge 2 Target Temp"
    icon: "mdi:thermometer"
  - platform: dometic_cfx_wifi
    dometic_cfx_wifi_id: fridge1
    type: DC_VOLTAGE
    name: "Fridge DC Voltage"
    icon: "mdi:flash"

binary_sensor:
  - platform: dometic_cfx_wifi
    dometic_cfx_wifi_id: fridge1
    type: COMPARTMENT_0_DOOR_OPEN
    name: "Fridge 1 Door"
    icon: "mdi:door"
  - platform: dometic_cfx_wifi
    dometic_cfx_wifi_id: fridge1
    type: COMPARTMENT_1_DOOR_OPEN
    name: "Fridge 2 Door"
    icon: "mdi:door"

text_sensor:
  - platform: dometic_cfx_wifi
    dometic_cfx_wifi_id: fridge1
    type: DEVICE_NAME
    name: "Fridge 1 Name"