esphome:
  name: esphome-web-cfx3
  friendly_name: ESPHome Dometic CFX3 WiFi
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
 - source: github://andrewbackway/esphome-dometic_cfx3_wifi
   refresh: 1s

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: TODO
  password: TODO

dometic-cfx3-wifi:
  host: "10.1.0.55"
  cooler_power:
    name: "CFX Power"
  device_name:
    name: "CFX Device Name"
  dc_voltage:
    name: "CFX DC Voltage"
    icon: "mdi:flash"
  comp0_temp:
    name: "CFX Compartment 1 Temp"
    icon: "mdi:thermometer"
  comp1_temp:
    name: "CFX Compartment 2 Temp"
    icon: "mdi:thermometer"
  comp0_set_temp:
    name: "CFX Compartment 1 Target Temp"
    icon: "mdi:thermometer"
  comp1_set_temp:
    name: "CFX Compartment 2 Target Temp"
    icon: "mdi:thermometer"
  comp0_door_open:
    name: "CFX Compartment 1 Door"
    icon: "mdi:door"
  comp1_door_open:
    name: "CFX Compartment 2 Door"
    icon: "mdi:door"
  comp0_power:
    name: "CFX Compartment 1 Power"
  comp1_power:
    name: "CFX Compartment 2 Power"